import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['New Order', 'sans-serif'],
        heading: ['New Order', 'sans-serif'],
      },
      fontSize: {
        'hero-xl': ['3.75rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'hero-lg': ['3.25rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'hero-md': ['2.5rem', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '600' }],
        'subtitle': ['1.375rem', { lineHeight: '1.5', fontWeight: '300' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body': ['1rem', { lineHeight: '1.6', fontWeight: '300' }],
        'nav': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'button': ['1.0625rem', { lineHeight: '1.4', fontWeight: '500' }],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          warm: "hsl(var(--accent-warm))",
          gold: "hsl(var(--accent-gold))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
          surface: "hsl(var(--card-surface))",
        },
        'bg-dark': "hsl(var(--bg-dark))",
        'card-surface': "hsl(var(--card-surface))",
        'kalea-logo': "hsl(var(--kalea-logo))",
        'kalea-dark': "hsl(var(--kalea-dark))",
        'kalea-tan': "hsl(var(--kalea-tan))",
        'kalea-cream': "hsl(var(--kalea-cream))",
        'kalea-grey': "hsl(var(--kalea-grey))",
        'status-excellent': "hsl(var(--status-excellent))",
        'status-good': "hsl(var(--status-good))",
        'status-poor': "hsl(var(--status-poor))",
        // ---- CRM Design System (Monday/Linear premium SaaS) ----
        crm: {
          bg:          "var(--crm-bg)",
          'bg-soft':   "var(--crm-bg-soft)",
          surface:     "var(--crm-surface)",
          'surface-2': "var(--crm-surface-2)",
          hover:       "var(--crm-surface-hover)",
          ink:         "var(--crm-ink)",
          'ink-strong':"var(--crm-ink-strong)",
          'ink-muted': "var(--crm-ink-muted)",
          'ink-subtle':"var(--crm-ink-subtle)",
          'ink-label': "var(--crm-ink-label)",
          border:      "var(--crm-border)",
          'border-strong': "var(--crm-border-strong)",
          primary:     "var(--crm-primary)",
          'primary-600': "var(--crm-primary-600)",
          'primary-700': "var(--crm-primary-700)",
          'primary-soft': "var(--crm-primary-soft)",
          success:     "var(--crm-success)",
          'success-soft': "var(--crm-success-soft)",
          warning:     "var(--crm-warning)",
          'warning-soft': "var(--crm-warning-soft)",
          danger:      "var(--crm-danger)",
          'danger-soft': "var(--crm-danger-soft)",
          info:        "var(--crm-info)",
          'info-soft': "var(--crm-info-soft)",
          purple:      "var(--crm-purple)",
          'purple-soft': "var(--crm-purple-soft)",
          teal:        "var(--crm-teal)",
          'teal-soft': "var(--crm-teal-soft)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        crm:      "var(--crm-radius)",
        'crm-sm': "var(--crm-radius-sm)",
        'crm-lg': "var(--crm-radius-lg)",
        'crm-xl': "var(--crm-radius-xl)",
        'crm-2xl':"var(--crm-radius-2xl)",
      },
      boxShadow: {
        'crm-xs': 'var(--crm-shadow-xs)',
        'crm-sm': 'var(--crm-shadow-sm)',
        'crm-md': 'var(--crm-shadow-md)',
        'crm-lg': 'var(--crm-shadow-lg)',
        'crm-xl': 'var(--crm-shadow-xl)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: "0" },
        },
        "nudge-x": {
          "0%, 100%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(3px)" },
        },
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "crm-fade-up": {
          "0%":   { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "crm-scale-in": {
          "0%":   { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "crm-slide-in-right": {
          "0%":   { opacity: "0", transform: "translateX(12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "nudge-x": "nudge-x 4.5s ease-in-out infinite",
        marquee: "marquee 45s linear infinite",
        "crm-fade-up":     "crm-fade-up 260ms cubic-bezier(0.22, 1, 0.36, 1)",
        "crm-scale-in":    "crm-scale-in 220ms cubic-bezier(0.22, 1, 0.36, 1)",
        "crm-slide-in":    "crm-slide-in-right 240ms cubic-bezier(0.22, 1, 0.36, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
