// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/sb.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-leads.ts
import { z } from "npm:zod@^4.4.3";
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List leads",
  description: "List recent leads from the Kal\u0113a CRM. Optional filters: status, pipeline_stage, search (matches name/email/city), limit (default 25, max 100).",
  inputSchema: {
    status: z.string().optional().describe("Filter by lead status (e.g. 'nuovo', 'qualificato')."),
    pipeline_stage: z.string().optional().describe("Filter by pipeline stage (e.g. 'cold', 'warm', 'hot')."),
    search: z.string().optional().describe("Search term matched against name, email or city."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, pipeline_stage, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("leads").select("id, name, email, phone, city, province, status, pipeline_stage, source, notes, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (pipeline_stage) q = q.eq("pipeline_stage", pipeline_stage);
    if (search) q = q.or(`name.ilike.%${search}%,email.ilike.%${search}%,city.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} leads

${JSON.stringify(data, null, 2)}` }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-quotes.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_quotes_default = defineTool2({
  name: "list_quotes",
  title: "List quotes",
  description: "List Kal\u0113a quotes (preventivi). Optional filters: status (draft/sent/accepted/converted/rejected/expired), search (matches quote_number / client_name), limit (default 25, max 100).",
  inputSchema: {
    status: z2.string().optional(),
    search: z2.string().optional(),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("quotes").select("id, quote_number, client_name, status, total_amount, vat_amount, vat_included, valid_until, created_at, created_by").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (search) q = q.or(`quote_number.ilike.%${search}%,client_name.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} quotes

${JSON.stringify(data, null, 2)}` }],
      structuredContent: { quotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-customers.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_customers_default = defineTool3({
  name: "list_customers",
  title: "List customers",
  description: "List Kal\u0113a customers. Optional filters: status, search (matches company_name / first_name / last_name / email), limit (default 25, max 100).",
  inputSchema: {
    status: z3.string().optional(),
    search: z3.string().optional(),
    limit: z3.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("customers").select("id, company_name, first_name, last_name, email, phone, city, province, status, total_value, total_margin, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (search) q = q.or(`company_name.ilike.%${search}%,first_name.ilike.%${search}%,last_name.ilike.%${search}%,email.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} customers

${JSON.stringify(data, null, 2)}` }],
      structuredContent: { customers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-sites.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var list_sites_default = defineTool4({
  name: "list_construction_sites",
  title: "List construction sites",
  description: "List Kal\u0113a construction sites (cantieri). Optional filters: status, priority, search (matches title/project_name/city), limit (default 25, max 100).",
  inputSchema: {
    status: z4.string().optional(),
    priority: z4.string().optional(),
    search: z4.string().optional(),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, priority, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("construction_sites").select("id, title, project_name, status, priority, city, province, planned_start_date, planned_end_date, customer_id, salesperson_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (priority) q = q.eq("priority", priority);
    if (search) q = q.or(`title.ilike.%${search}%,project_name.ilike.%${search}%,city.ilike.%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `${data?.length ?? 0} sites

${JSON.stringify(data, null, 2)}` }],
      structuredContent: { sites: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
var create_lead_default = defineTool5({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new lead in the Kal\u0113a CRM. Requires at least name and email.",
  inputSchema: {
    name: z5.string().min(1),
    email: z5.string().email(),
    phone: z5.string().optional(),
    city: z5.string().optional(),
    province: z5.string().optional(),
    company_name: z5.string().optional(),
    interest: z5.string().optional().describe("Product / service of interest."),
    notes: z5.string().optional(),
    source: z5.string().optional().describe("Lead source, e.g. 'mcp', 'website'. Defaults to 'mcp'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("leads").insert({
      name: input.name,
      email: input.email.toLowerCase(),
      phone: input.phone ?? null,
      city: input.city ?? null,
      province: input.province ?? null,
      company_name: input.company_name ?? null,
      interest: input.interest ?? null,
      notes: input.notes ?? null,
      source: input.source ?? "mcp",
      status: "nuovo",
      pipeline_stage: "warm"
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lead created: ${data.id}` }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ulvnhevuqhcmgxuexdil";
var mcp_default = defineMcp({
  name: "kalea-crm-mcp",
  title: "Kal\u0113a CRM",
  version: "0.1.0",
  instructions: "Access the Kal\u0113a CRM: leads, quotes (preventivi), customers, and construction sites (cantieri). Read-only queries plus lead creation. All requests run as the signed-in user with RLS enforced.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, list_quotes_default, list_customers_default, list_sites_default, create_lead_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
